#!/usr/bin/env node

var path = require('path'),
    fs = require('fs'),
    cp = require('child_process'),
    mustache = require('mustache'),
    async = require('async');

var GOVUK_TOOLKIT = path.dirname(require.resolve('govuk_frontend_toolkit/package.json'));

function renderTemplate(callback) {
    var src = path.resolve(GOVUK_TOOLKIT, './stylesheets/');

    fs.readFile(path.resolve(__dirname, './assets/stylesheets/mixins.scss.tpl'), function (err, input) {
        if (err) {
            callback(err);
        } else {
            fs.writeFile(path.resolve(__dirname, './assets/stylesheets/mixins.scss'), mustache.render(input.toString(), { 'govuk-toolkit-path': src }), function (err) {
                if (err) {
                    callback(err);
                } else {
                    callback();
                }
            });
        }
    });
}

function copyImages(callback) {
    var src = path.resolve(GOVUK_TOOLKIT, './images/');

    fs.mkdir(path.resolve(__dirname, './assets/images/icons'), function (err) {
        if (err && err.code !== 'EEXIST') {
            callback(err);
        } else {
            cp.exec('cp ' + src + '/* ./assets/images/icons/ -R', callback);
        }
    });

}

async.series([
    renderTemplate,
    copyImages
], function (err) {
    if (err) {
        throw err;
    }
});
